### ISSUE TITLE
[Bug]: crash with itemphysics (ClassNotFoundException: EntityItem)

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Galacticraft-Continuation#5]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.1.3

### Log or Crash Report

https://mclo.gs/CH0ImsS

### Reproduction steps

download itemphysics and Galacticraft-Continuation, try to launch - crash

**Comment by quentin452** [comment]
for me i don't get crash

**Comment by quentin452** [comment]
ah ok the crash appear with ItemPhysik full not the lite

**Comment by quentin452** [comment]
compat added in V4.1.4
